### PR TITLE
Feature csi expand

### PR DESCRIPTION
**Pull request by st0ne-dot-at**
I've implemented the volume expand feature from the kubernetes csi specification. https://github.com/container-storage-interface/spec/blob/master/lib/go/csi/csi.pb.go
This is my first contact with go so there is review work to do. ;)

Best regards,
Rob

### CODE REVIEW

**Comment by st0ne-dot-at** [comment]
tested with the folloing environment:
kubernetes: 1.19.4
oVirt: 4.3

**Comment by bennyz** [comment]
@st0ne-dot-at, this is great, thanks!

There is a small problem though, this repo is far behind https://github.com/openshift/ovirt-csi-driver where we have been doing our development for a while now. I can sync this repo with the openshift fork, but I'd want this change in the openshift fork as well.

Are you using it only with kubernetes or with OKD/openshift as well?

**Comment by st0ne-dot-at** [comment]
> @st0ne-dot-at, this is great, thanks!
> 
> There is a small problem though, this repo is far behind https://github.com/openshift/ovirt-csi-driver where we have been doing our development for a while now. I can sync this repo with the openshift fork, but I'd want this change in the openshift fork as well.
> 
> Are you using it only with kubernetes or with OKD/openshift as well?

I'm using kunernetes at the moment.

**Comment by st0ne-dot-at** [comment]
> @st0ne-dot-at, this is great, thanks!
> 
> There is a small problem though, this repo is far behind https://github.com/openshift/ovirt-csi-driver where we have been doing our development for a while now. I can sync this repo with the openshift fork, but I'd want this change in the openshift fork as well.
> 
> Are you using it only with kubernetes or with OKD/openshift as well?

Is there openshift related code in https://github.com/openshift/ovirt-csi-driver? If not, i can redo my work on that repo.
Is this project discontinued?

**Comment by bennyz** [comment]
> > @st0ne-dot-at, this is great, thanks!
> > There is a small problem though, this repo is far behind https://github.com/openshift/ovirt-csi-driver where we have been doing our development for a while now. I can sync this repo with the openshift fork, but I'd want this change in the openshift fork as well.
> > Are you using it only with kubernetes or with OKD/openshift as well?
> 
> Is there openshift related code in https://github.com/openshift/ovirt-csi-driver? If not, i can redo my work on that repo.
There shouldn't be
> Is this project discontinued?
It's not discontinued per se, it was temporary until our operator was merged, and now this driver is installed and managed by the operator. The assumption was that most users are using this with OKD/openshift, so the plan was to use this repo as sort of an "upstream" for the openshift repo, but it didn't seem like there was much demand for this. But if there is interest, I will resync this repo with the fork and this will be the first upstream feature

**Comment by st0ne-dot-at** [comment]
@bennyz : I've just testet my changes with the openshift/ovirt-csi-driver ... works as well. So if you wish i can do a PR against the openshift/ovirt-csi-driver repo. It's your choice!

**Comment by st0ne-dot-at** [comment]
@bennyz : I've redone my work on the  openshift/ovirt-csi-driver repository. Do you want me to do a PR to the  openshift/ovirt-csi-driver repository?

**Comment by bennyz** [comment]
> @bennyz : I've redone my work on the openshift/ovirt-csi-driver repository. Do you want me to do a PR to the openshift/ovirt-csi-driver repository?

yes, thanks. I'll have test it in openshift though as the driver is installed automatically there.
I will also resync this repo so it can be merged here as a "tech preview" for now

**Comment by st0ne-dot-at** [comment]
@bennyz : hint: my external-resizer configuration in the ovirt-plugin StatefullSet

    ...
    template:
      spec:
        containers:
        - name: csi-external-resizer
          imagePullPolicy: Always
          image: quay.io/k8scsi/csi-resizer:v1.0.1
          args:
            - "--v=4"
            - "--csi-address=/csi/csi.sock"
            - "--handle-volume-inuse-error=false"
            - "--leader-election"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
    ....

**Comment by st0ne-dot-at** [comment]
@bennyz : It's not clear for me what to do now. I'm not able to fork https://github.com/openshift/ovirt-csi-driver because i've forked this repo. So i can't make a PR on the openshift/ovirt-csi-driver repo.

**Comment by bennyz** [comment]
> @bennyz : It's not clear for me what to do now. I'm not able to fork https://github.com/openshift/ovirt-csi-driver because i've forked this repo. So i can't make a PR on the openshift/ovirt-csi-driver repo.

You can create a branch in your fork that is based on the openshift fork, then create the PR for this branch (you should have a dropdown list to select the base repo)

**Comment by st0ne-dot-at** [comment]
> > @bennyz : It's not clear for me what to do now. I'm not able to fork https://github.com/openshift/ovirt-csi-driver because i've forked this repo. So i can't make a PR on the openshift/ovirt-csi-driver repo.
> 
> You can create a branch in your fork that is based on the openshift fork, then create the PR for this branch (you should have a dropdown list to select the base repo)

thx ... will try that!

**Comment by sandrobonazzola** [comment]
This repository is inactive, please refer to: https://github.com/openshift/ovirt-csi-driver

**Pull request closed without merging**
