### PR TITLE
Add standard ovirt CI

### PR DESCRIPTION
**Pull request by rgolangh**

### CODE REVIEW

**Comment by rgolangh** [comment]
@bennyz that's a start. We need to send a patch to ovirt jenkins repo I think

**Comment by rgolangh** [comment]
this pr can merge one we have a build finished and container published to quay under ovirt

**Comment by rgolangh** [comment]
/hold
I'm checking if this can go under openshift ci

**Comment by sandrobonazzola** [comment]
@rgolangh can we drop this then?

**Comment by rgolangh** [comment]
let's first see that I have something successful?

**Comment by rgolangh** [comment]
dumping in favour of openshift-ci

**Pull request closed without merging**
